// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJSZGxTgQqykk4ayMfx2ZL6b6K0aqLeUU',
    appId: '1:312495723278:web:42bad60ae022a9a4283d5f',
    messagingSenderId: '312495723278',
    projectId: 'proyecto2-a6cf9',
    authDomain: 'proyecto2-a6cf9.firebaseapp.com',
    storageBucket: 'proyecto2-a6cf9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLnxbWV9fRy1INVA4XfhPgyY3AHO06o-s',
    appId: '1:312495723278:android:b62d64ad6bdbebfb283d5f',
    messagingSenderId: '312495723278',
    projectId: 'proyecto2-a6cf9',
    storageBucket: 'proyecto2-a6cf9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAq9BWOAV7IPsZGKCeRHNKkGlnAzvTtPbc',
    appId: '1:312495723278:ios:2821624af46aec0c283d5f',
    messagingSenderId: '312495723278',
    projectId: 'proyecto2-a6cf9',
    storageBucket: 'proyecto2-a6cf9.appspot.com',
    iosClientId: '312495723278-119ulsi9mp8fk179rgr72feudfbejae4.apps.googleusercontent.com',
    iosBundleId: 'com.example.damU4Proyecto217401335',
  );
}
